### PR TITLE
Don't trigger CINK002 for double quotes in comments

### PR DESCRIPTION
**Pull request by JeanMertz**

### CODE REVIEW

**Comment by JeanMertz** [comment]
Didn't see the existing regexp initially. Fixed now.

**Comment by sethvargo** [comment]
@JeanMertz 
- :+1: on the multi-level conditionals
- LGTM

I actually don't encounter this rule anymore, because I use Rubocop as a more general style linting rule. I'm happy to click the merge button, but I'm going to defer to @clumpidy here :smile:

**Comment by JeanMertz** [comment]
Using Rubocop as well, now that I think of it. I might disable this one as well.

Still, for those who aren't using Rubocop yet.

**Comment by clumpidy** [comment]
I don't see a reason not to merge.  Thanks for the PR.

**Pull request merged**
